% contourStates.m
clc; clear all; close all;

% Load the data generated by mainSweep.m
load('sweepResults/sweepDataWorkspace.mat');

% ========================= RECONSTRUCT MISSING VARIABLES =========================
% Calculate nSubplots based on the labels we saved
nSubplots = length(plotLabs);

% Re-extract the terminal states from the timeSeriesData 
states = cell(1, nSubplots);
for k = 1:nSubplots
    states{k} = zeros(size(alphaMesh));
    for r = 1:size(alphaMesh, 1)
        for c = 1:size(alphaMesh, 2)
            states{k}(r,c) = timeSeriesData{r,c}.vars(end, k);
        end
    end
end
% =================================================================================

% ========================= Figure Setup =========================
% Set default interpreters to LaTeX for beautiful text rendering
set(groot, 'defaultAxesTickLabelInterpreter', 'latex');
set(groot, 'defaultLegendInterpreter', 'latex');
set(groot, 'defaultTextInterpreter', 'latex');

% Create a single cleanly sized figure for the 3x4 grid
stateSurfFig = figure('Name', 'Quadrotor Terminal States');
set(stateSurfFig, 'Color', 'w', 'Units', 'inches', 'Position', [0, 2, 9, 4.5]);

% Use tiledlayout for tight grouping
t = tiledlayout(stateSurfFig, 3, 4, 'Padding', 'compact', 'TileSpacing', 'compact');

% Font and Tick Sizes
tickSz = 9;
fntSz = 11;

% Labels for the X-axis
xTickLabelsList = {'$\alpha_{1}$', '$\alpha_{2}$', '$\alpha_{3}$', ...
                   '$\alpha_{4}$', '$\alpha_{5}$', '$\alpha_{6}$', '$\alpha_{7}$'};

% ========================= Plotting Loop =========================
for i = 1:nSubplots
    ax = nexttile(t, i);
    
    % Plot the surface as a flat 2D grid using the imported variables directly
    surf(ax, alphaMesh, d0Mesh, zeros(size(states{i})), states{i});
    view(ax, 2);
    
    % Formatting to match the discrete grid look from the paper
    shading(ax, 'flat');      % Flat colors for each cell
    set(ax, 'Layer', 'top');  % Puts grid lines over the color
    grid(ax, 'on');
    axis(ax, 'tight');
    
    % Colorbar setup
    colormap(ax, 'jet');
    c = colorbar(ax);
    c.Label.String = plotLabs(i);
    c.Label.Interpreter = 'latex';
    c.FontSize = tickSz;
    c.Label.FontSize = fntSz;
    
    % Apply limits using imported variables
    xlim(ax, [1, 7]);
    ylim(ax, [min(d0_vec), max(d0_vec)]);
    
    % Apply standard ticks using imported variables
    xticks(ax, alpha_i_vec);
    yticks(ax, d0_vec);
    
    % ---------------- Axis Labeling Logic ----------------
    % Only show Y-labels and Y-ticks on the LEFT column (1, 5, 9)
    if ismember(i, [1, 5, 9])
        ylabel(ax, 'Distances (m)', 'FontSize', fntSz);
        ax.YAxis.FontSize = tickSz;
    else
        yticklabels(ax, {});
    end
    
    % Only show X-labels and X-ticks on the BOTTOM row (9, 10, 11, 12)
    if ismember(i, [9, 10, 11, 12])
        xlabel(ax, 'Blast Angles', 'FontSize', fntSz);
        xticklabels(ax, xTickLabelsList);
        ax.XAxis.FontSize = tickSz;
    else
        xticklabels(ax, {});
    end
end

% ========================= Export =========================
% Save the final cleaned figure
exportgraphics(stateSurfFig, fullfile('sweepResults', 'allStatesSurface.pdf'), 'Resolution', 600);
exportgraphics(stateSurfFig, fullfile('sweepResults', 'allStatesSurface.png'), 'Resolution', 600);