% plotAllTimeSeries.m
clc; clear all; close all;

% Load the data generated by mainSweep.m
load('sweepResults/sweepDataWorkspace.mat');

% Font and Tick Sizes
tickSz = 9;
fntSz = 11;

% --- OVERRIDE LABELS FOR PROPER LATEX RENDERING ---
titleLabs = ["$\Delta X$", "$\dot{X}$", "$\theta$", "$p$", ...
             "$\Delta Y$", "$\dot{Y}$", "$\phi$", "$q$", ...
             "$\Delta Z$", "$\dot{Z}$", "$\psi$", "$r$"];
% --------------------------------------------------

% Setup Figure
fig = figure('Name', 'All Sims Over Time');
set(fig, 'Color', 'w', 'Units', 'inches', 'Position', [0 1 14 8]);
set(groot, 'defaultAxesTickLabelInterpreter', 'latex');
set(groot, 'defaultLegendInterpreter', 'latex');
set(groot, 'defaultTextInterpreter', 'latex');

tiledlayout(3, 4, 'Padding', 'compact', 'TileSpacing', 'compact');
lw = 0.8; 

% Create a colormap for the distances 
distColors = turbo(length(d0_vec)); 

% Loop through each of the 12 states
for stateIdx = 1:length(plotLabs)
    ax = nexttile;
    hold on;
    grid on;
    
    % Loop through every simulation run in the mesh
    for r = 1:size(alphaMesh, 1)
        currentColor = [distColors(r, :), 0.4]; 
        for c = 1:size(alphaMesh, 2)
            t_data = timeSeriesData{r,c}.t * 1000; % Convert to ms
            var_data = timeSeriesData{r,c}.vars(:, stateIdx);
            plot(t_data, var_data, 'LineWidth', lw, 'Color', currentColor); 
        end
    end
    
    % Apply Font and Tick Sizes
    ax.XAxis.FontSize = tickSz;
    ax.YAxis.FontSize = tickSz;
    
    ylabel(plotLabs(stateIdx), 'Interpreter', 'latex', 'FontSize', fntSz);
    if stateIdx > 8
        xlabel("Time (ms)", 'Interpreter', 'latex', 'FontSize', fntSz);
    end
    
    title(titleLabs(stateIdx), 'Interpreter', 'latex', 'FontSize', fntSz);
    
    % Create a clean legend ONLY on the final subplot
    if stateIdx == 12
        for k = 1:length(d0_vec)
            dummyPlot(k) = plot(NaN, NaN, 'Color', distColors(k,:), 'LineWidth', 3, ...
                'DisplayName', sprintf('$d_0 = %g$ m', d0_vec(k)));
        end
        
        lgd = legend(dummyPlot, 'Location', 'eastoutside', 'NumColumns', 1, 'Interpreter', 'latex');
        lgd.Layout.Tile = 'east'; 
        lgd.FontSize = tickSz; % Apply tick size to legend text
    end
end

savePlot('allTimeSeriesPlot', 'sweepResults')