% plotSelectedTimeSeries.m
clc; clear all; close all;

% ==================== USER SELECTION ====================
sweepType = 'alpha';   % Choose 'alpha' or 'd0' to hold constant
fixedValue = 3;        % The value of the parameter to hold constant 
% ========================================================

% Load the data generated by mainSweep.m
load('sweepResults/sweepDataWorkspace.mat');

% Font and Tick Sizes
tickSz = 9;
fntSz = 11;

% --- OVERRIDE LABELS FOR PROPER LATEX RENDERING ---
titleLabs = ["$\Delta X$", "$\dot{X}$", "$\theta$", "$p$", ...
             "$\Delta Y$", "$\dot{Y}$", "$\phi$", "$q$", ...
             "$\Delta Z$", "$\dot{Z}$", "$\psi$", "$r$"];
% --------------------------------------------------

% Find the indices of the fixed variable
if strcmp(sweepType, 'alpha')
    colIdx = find(alpha_i_vec == fixedValue);
    if isempty(colIdx)
        error('Fixed value not found in alpha_i_vec. Available: %s', mat2str(alpha_i_vec));
    end
    simIndices = arrayfun(@(r) [r, colIdx], 1:length(d0_vec), 'UniformOutput', false);
    legendPrefix = 'd_0 = ';
    legendSuffix = ' m';
    varyingVals = d0_vec;
    superTitle = sprintf('Fixed Blast Angle: $\\alpha_%d$', fixedValue);
else
    rowIdx = find(d0_vec == fixedValue);
    if isempty(rowIdx)
        error('Fixed value not found in d0_vec. Available: %s', mat2str(d0_vec));
    end
    simIndices = arrayfun(@(c) [rowIdx, c], 1:length(alpha_i_vec), 'UniformOutput', false);
    legendPrefix = '\alpha_';
    legendSuffix = '';
    varyingVals = alpha_i_vec;
    superTitle = sprintf('Fixed Distance: %.1f m', fixedValue);
end

% Setup Figure
fig = figure('Name', 'Selected Sweep Over Time');
set(fig, 'Color', 'w', 'Units', 'inches', 'Position', [0 1 14 8]);
set(groot, 'defaultAxesTickLabelInterpreter', 'latex');
set(groot, 'defaultLegendInterpreter', 'latex');
set(groot, 'defaultTextInterpreter', 'latex');

t = tiledlayout(3, 4, 'Padding', 'compact', 'TileSpacing', 'compact');
% Make the super title slightly larger than the standard font size
title(t, superTitle, 'Interpreter', 'latex', 'FontSize', fntSz + 3); 

lw = 1.5;
colors = lines(length(varyingVals)); 

% Loop through each of the 12 states
for stateIdx = 1:length(plotLabs)
    ax = nexttile;
    hold on;
    grid on;
    
    % Loop through the selected slice of data
    for i = 1:length(simIndices)
        r = simIndices{i}(1);
        c = simIndices{i}(2);
        
        t_data = timeSeriesData{r,c}.t * 1000; % Convert to ms
        var_data = timeSeriesData{r,c}.vars(:, stateIdx);
        
        plotName = sprintf('$%s%g%s$', legendPrefix, varyingVals(i), legendSuffix);
        plot(t_data, var_data, 'LineWidth', lw, 'Color', colors(i,:), 'DisplayName', plotName);
    end
    
    % Apply Font and Tick Sizes
    ax.XAxis.FontSize = tickSz;
    ax.YAxis.FontSize = tickSz;
    
    ylabel(plotLabs(stateIdx), 'Interpreter', 'latex', 'FontSize', fntSz);
    if stateIdx > 8
        xlabel("Time (ms)", 'Interpreter', 'latex', 'FontSize', fntSz);
    end
    
    title(titleLabs(stateIdx), 'Interpreter', 'latex', 'FontSize', fntSz);
    
    % Only put the legend on the very last subplot
    if stateIdx == 12
        lgd = legend('Location', 'eastoutside', 'Interpreter', 'latex');
        lgd.Layout.Tile = 'east';
        lgd.FontSize = tickSz; % Apply tick size to legend text
    end
end

savePlot('selectedTimeSeriesPlot', 'sweepResults')