% generate_figures.m
% Generates 3 MDPI-formatted vector PDFs for side-by-side assembly
clear; clc; close all;
addpath('../');
figDir = 'figs';

% Ensure subroutines are accessible
addpath('subroutines'); 

if ~exist(figDir, 'dir')
    mkdir(figDir);
end

% Load the clean data generated by generate_data.m
if ~isfile(fullfile(figDir, 'plot_data.mat'))
    error('plot_data.mat not found in %s. Please run generate_data.m first.', figDir);
end
load(fullfile(figDir, 'plot_data.mat'));

% Global LaTeX formatting
set(groot, 'defaultAxesTickLabelInterpreter', 'latex');
set(groot, 'defaultLegendInterpreter', 'latex');
set(groot, 'defaultTextInterpreter', 'latex');

% Universal Plot Params
lw = 1.4;
t_ms = t * 1000;
max_time_ms = 100; % Bounds for the pressure/velocity x-axis

disp('Generating figures...');

%% ================== Figure 1: Pressure Comparison ==================
fig1 = figure('Name', 'Pressure Comp');
hold on; grid on;

plot(t_ms, 0.001 * p_cfd, '-.', 'Color', 'k', 'LineWidth', lw, 'DisplayName', 'CFD');
plot(t_ms, 0.001 * optP, '--', 'Color', 'r', 'LineWidth', lw, 'DisplayName', 'Fit');
plot(t_ms, 0.001 * modelP, '-', 'Color', 'b', 'LineWidth', lw, 'DisplayName', 'Model');

xlabel('Time (ms)');
ylabel('Overpressure (kPa)');
% title('$r = 15$ m', 'Interpreter', 'latex');
xlim([0, max_time_ms]);
lgd1 = legend('Location', 'northeast');
lgdSize = [15,18];
lgd1.ItemTokenSize = lgdSize;

% Format and Export
formatMDPIFigure(fig1, 'third');
exportgraphics(fig1, fullfile(figDir, 'pressure_comp.pdf'), 'ContentType', 'vector');

%% ================== Figure 2: Velocity Comparison ==================
fig2 = figure('Name', 'Velocity Comp');
hold on; grid on;

mach2ms = 343;

plot(t_ms, v_cfd, '-.', 'Color', 'k', 'LineWidth', lw, 'DisplayName', 'CFD');
plot(t_ms, optV * mach2ms, '--', 'Color', 'r', 'LineWidth', lw, 'DisplayName', 'Fit');
plot(t_ms, modelV * mach2ms, '-', 'Color', 'b', 'LineWidth', lw, 'DisplayName', 'Model');

xlabel('Time (ms)');
ylabel('Wind Magnitude (m/s)');
% title('$r = 15$ m', 'Interpreter', 'latex');
xlim([0, max_time_ms]);
lgd2 = legend('Location', 'northeast');
lgd2.ItemTokenSize = lgdSize;

% Format and Export
formatMDPIFigure(fig2, 'third');
exportgraphics(fig2, fullfile(figDir, 'velocity_comp.pdf'), 'ContentType', 'vector');

%% ================== Figure 3: c-Fit Scatter ==================
fig3 = figure('Name', 'Propagation Speed');
hold on; grid on;

plot(c_r, c_c, 'k.', 'DisplayName', 'Calculated c');
% plot(c_r, c_fit, 'r--', 'LineWidth', lw, 'DisplayName', sprintf('Fit = %2.0f (m/s)~~', c_fit_end_val));
plot(c_r, c_fit, 'r--', 'LineWidth', lw, 'DisplayName', sprintf('Fit'));

% Plot the updated 3-Sigma bounds
% plot(c_r, c_3sigPos, 'b--', 'LineWidth', lw, 'DisplayName', '$3\sigma$');
% plot(c_r, c_3sigNeg, 'b--', 'LineWidth', lw, 'HandleVisibility', 'off');

xlabel('$r$ (m)');
ylabel('$c$ (m/s)');
xlim([0, 25]);
lgd3 = legend('Location', 'northeast');
lgd3.ItemTokenSize = lgdSize;

% Format and Export
formatMDPIFigure(fig3, 'third');
% exportgraphics(fig3, fullfile(figDir, 'c_fit.pdf'), 'ContentType', 'vector');
savePlot(fig3, 'c_fit', figDir, false, true)

disp('All figures successfully exported to the figs/ directory!');